# Generated by Django 3.0.4 on 2020-03-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('rfc', models.CharField(max_length=13)),
                ('puesto', models.CharField(choices=[('CH', 'Chofer'), ('TM', 'Tecnico de mantenimiento'), ('SC', 'Supervisor de Chofer'), ('JM', 'Jefe de mantenimiento'), ('GT', 'Gerente de transporte')], default='CH', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('Di', 'Disponible'), ('Em', 'En mantenimiento'), ('Et', 'En transporte')], default='Di', max_length=2)),
            ],
        ),
    ]
