# Generated by Django 3.0.4 on 2020-03-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Disponible'), (1, 'En mantenimiento'), (2, 'En transporte')], default=0, max_length=1),
        ),
    ]
