# Generated by Django 3.0.4 on 2020-03-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0002_auto_20200325_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='estado',
            field=models.CharField(choices=[('0', 'Disponible'), ('1', 'En mantenimiento'), ('2', 'En transporte')], default='0', max_length=1),
        ),
    ]
