# Generated by Django 3.0.4 on 2020-03-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0003_auto_20200325_1341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agenda',
            new_name='Agendas',
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='estado',
            field=models.CharField(choices=[('Di', 'Disponible'), ('Ma', 'En mantenimiento'), ('Tr', 'En transporte')], default='Di', max_length=2),
        ),
    ]
