# Generated by Django 3.0.4 on 2020-03-25 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0004_auto_20200325_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendas',
            name='chofer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_transporte.Empleados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendas',
            name='vehiculo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_transporte.Vehiculos'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Transportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_inicio', models.CharField(max_length=50)),
                ('lugar_destino', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PH', 'Por hacer'), ('EP', 'En proceso'), ('Te', 'Terminado'), ('Fi', 'Firmado'), ('Pr', 'Problema')], default='PH', max_length=2)),
                ('asignado_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_transporte.Agendas')),
            ],
        ),
    ]
