# Generated by Django 3.0.4 on 2020-03-25 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0005_auto_20200325_1430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transportes',
            new_name='Servicios',
        ),
    ]
