# Generated by Django 3.0.4 on 2020-03-26 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0006_auto_20200325_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agendas',
            new_name='Checklist',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='asignado_a',
            new_name='checklist',
        ),
    ]
