# Generated by Django 3.0.4 on 2020-04-01 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0007_auto_20200325_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='chofer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_transporte.Empleados'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='vehiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_transporte.Vehiculos'),
        ),
    ]
