# Generated by Django 3.0.4 on 2020-04-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0008_auto_20200401_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicios',
            name='estado',
            field=models.CharField(choices=[('PH', 'Por hacer'), ('EP', 'En proceso'), ('TE', 'Terminado'), ('FI', 'Firmado'), ('PR', 'Problema')], default='PH', max_length=2),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='estado',
            field=models.CharField(choices=[('DI', 'Disponible'), ('NO', 'No Disponible')], default='DI', max_length=2),
        ),
    ]
