# Generated by Django 3.0.4 on 2020-05-22 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0012_auto_20200513_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitudes',
        ),
    ]
