# Generated by Django 3.0.4 on 2020-05-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0013_delete_solicitudes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='solicitante',
            new_name='cliente',
        ),
        migrations.AlterField(
            model_name='servicios',
            name='estado',
            field=models.CharField(choices=[('SS', 'Servicio Solicitado'), ('PH', 'Por hacer'), ('EP', 'En proceso'), ('TE', 'Terminado'), ('FI', 'Firmado')], default='PH', max_length=2),
        ),
    ]
