# Generated by Django 3.0.4 on 2020-05-29 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0015_remove_clientes_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='a_transportar',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='vehiculos',
            name='estado',
        ),
        migrations.AddField(
            model_name='servicios',
            name='mascota',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='disponible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombres',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='numero_tarjeta',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='estado',
            field=models.CharField(choices=[('SO', 'Solicitado'), ('AG', 'Agendado'), ('EJ', 'Ejecucion'), ('TE', 'Terminado'), ('FI', 'Firmado')], default='SO', max_length=2),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='lugar_destino',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='lugar_inicio',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_limite', models.DateTimeField()),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_transporte.Servicios')),
            ],
        ),
    ]
