# Generated by Django 3.0.4 on 2020-06-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0017_auto_20200529_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='horario_fin',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='horario_inicio',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_limite',
            field=models.DateField(),
        ),
    ]
