# Generated by Django 3.0.4 on 2020-05-29 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0017_auto_20200529_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='fecha_inicio',
            new_name='fecha_origen',
        ),
    ]
