# Generated by Django 3.0.4 on 2020-05-29 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0018_auto_20200529_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='lugar_inicio',
            new_name='lugar_origen',
        ),
    ]
