# Generated by Django 3.0.4 on 2020-06-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0018_auto_20200605_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='precio_transporte',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicios',
            name='tipo_transporte',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Catalago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('descripcion', models.CharField(max_length=50)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_transporte.Vehiculos')),
            ],
        ),
    ]
