# Generated by Django 3.0.4 on 2020-06-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0019_auto_20200605_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='precio_transporte',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='tipo_transporte',
        ),
    ]
