# Generated by Django 3.0.4 on 2020-06-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0020_auto_20200605_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalago',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
