# Generated by Django 3.0.4 on 2020-06-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0021_catalago_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalago',
            name='url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
