# Generated by Django 3.0.4 on 2020-06-10 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0023_remove_catalago_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='horario_fin',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9 AM'), (datetime.time(10, 0), '10 AM'), (datetime.time(11, 0), '11 AM'), (datetime.time(12, 0), '12 PM'), (datetime.time(13, 0), '1 PM'), (datetime.time(14, 0), '2 PM'), (datetime.time(15, 0), '3 PM'), (datetime.time(16, 0), '4 PM'), (datetime.time(17, 0), '5 PM'), (datetime.time(18, 0), '6 PM')]),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='horario_inicio',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9 AM'), (datetime.time(10, 0), '10 AM'), (datetime.time(11, 0), '11 AM'), (datetime.time(12, 0), '12 PM'), (datetime.time(13, 0), '1 PM'), (datetime.time(14, 0), '2 PM'), (datetime.time(15, 0), '3 PM'), (datetime.time(16, 0), '4 PM'), (datetime.time(17, 0), '5 PM'), (datetime.time(18, 0), '6 PM')]),
        ),
    ]
