# Generated by Django 3.0.4 on 2020-06-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0024_auto_20200609_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='venta_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
