# Generated by Django 3.0.4 on 2020-06-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0025_servicios_venta_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='venta_id',
            new_name='clave_servicio',
        ),
        migrations.AddField(
            model_name='servicios',
            name='departamento_servicio',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
