# Generated by Django 3.0.4 on 2020-06-12 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0026_auto_20200611_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='pago',
        ),
        migrations.AddField(
            model_name='clientes',
            name='codigo_seguridad',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2020, 6, 11)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='nombre_titular',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='numero_tarjeta',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='correo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='mascota',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='Pagos',
        ),
    ]
