# Generated by Django 3.0.4 on 2020-06-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0028_auto_20200612_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='clave_servicio',
            new_name='clave_detalle_venta',
        ),
    ]
