# Generated by Django 3.0.4 on 2020-06-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0029_auto_20200612_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='clave_detalle_venta',
            new_name='cve_detalle_venta',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='departamento_servicio',
        ),
        migrations.AddField(
            model_name='servicios',
            name='cve_servicio',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
