# Generated by Django 3.0.4 on 2020-06-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0030_auto_20200614_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='cve_servicio',
        ),
    ]
