# Generated by Django 3.0.4 on 2020-06-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0031_remove_servicios_cve_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='cve_detalle_venta',
            field=models.IntegerField(default=0),
        ),
    ]
