# Generated by Django 3.0.4 on 2020-06-18 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0019_auto_20200529_1347'),
        ('app_transporte', '0032_auto_20200615_0221'),
    ]

    operations = [
    ]
