# Generated by Django 3.0.7 on 2020-06-20 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0034_auto_20200618_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=40)),
                ('codigo_seguridad', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='codigo_seguridad',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='numero_tarjeta',
        ),
        migrations.AddField(
            model_name='servicios',
            name='pago',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_transporte.Pagos'),
            preserve_default=False,
        ),
    ]
