# Generated by Django 3.0.7 on 2020-06-21 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0035_auto_20200619_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='servicio',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_transporte.Servicios'),
        ),
    ]
