# Generated by Django 3.0.7 on 2020-06-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0037_auto_20200623_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='servicio',
        ),
        migrations.AlterField(
            model_name='servicios',
            name='mascota',
            field=models.CharField(max_length=30),
        ),
    ]
